set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

set -g set-clipboard on
set -g mouse on
set -g status-interval 3
set -g detach-on-destroy off

unbind C-b
set -g prefix C-a

unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind %
bind v split-window -h -c "#{pane_current_path}"
unbind \"
bind s split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r Left resize-pane -L 5
bind -r Right resize-pane -R 5
bind -r Up resize-pane -U 5
bind -r Down resize-pane -D 5
bind -r m resize-pane -Z

bind e choose-session
bind a last-window
bind K kill-session
bind t switch-client -l
bind x kill-pane
bind N new-session

bind c new-window -c "#{pane_current_path}"

bind y copy-mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

bind-key -r f run-shell "tmux neww tmux-sessionizer"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'

blue="#61afef"
red="#e06c75"
purple="#c678dd"
light="#414550"
cyan="#56b6c2"

set -g status-justify centre
# set -g status-position top
set -g status-style "bg=default"
set -g status-left "#[fg=${blue},bold] [#[fg=${red}]#S#[fg=${blue},bold]]"
set -g status-left-length 100
set -g status-right ""
set -g window-status-style "fg=${blue},bg=default"
set -g window-status-current-style "fg=${red},bold"
set -g message-style "fg=${purple},bg=default"

# set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
