gaps inner 10
default_border pixel 2
#corner_radius 5

set $primary "#0000A8"
set $light "#EBEEEB"
set $dark "#323034"
client.focused $primary $primary $primary $primary
client.unfocused $light $light $light $light
client.focused_inactive $dark $dark $dark $dark
client.urgent $primary $primary $primary
