gaps inner 10
default_border pixel 2
corner_radius 3
shadows enable

set $primary "#a24f0c"
set $light "#979ca2"
set $dark "#323034"
client.focused $primary $primary $primary $primary
client.unfocused $light $light $light $light
client.focused_inactive $dark $dark $dark $dark
client.urgent $primary $primary $primary
