# This better work...
xwayland enable
#exec xwaylandvideobridge &
exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway

exec wl-clip-persist --clipboard both
exec wl-paste --watch cliphist store
