#!/bin/bash
# NAME="Choose app"

apps_dir=~/.scripts/main_apps/

apps=$(ls $apps_dir)

selected_app=$(echo "$apps" | dmenu -c -i -l 10 )

if [ -n "$selected_app" ]; then
  "${apps_dir}${selected_app}"
fi
