#!/bin/bash

len=16;
chars="abcdefghijklmnopqrstuvwxyz0123456789*.,;:-_@$%&/\\[]{}()^*'\"!?|<>ABCDEFGHIJKLMNOPQRSTUVWXYZ=+";
passwd="";
if [ "$1" ]; then
  len=$1;
fi
for ((i=0;i<len;i++)); do
  passwd="${passwd}${chars:$(($RANDOM*${#chars}/32767)):1}";
done
echo $passwd;
