#!/usr/bin/env bash
# NAME="Run script"

SCRIPTS_DIR="$HOME/.scripts"

declare -A scripts
while IFS= read -r script; do
  desc=$(grep '^# NAME=' "$SCRIPTS_DIR/$script" | cut -d'"' -f2)
  if [ -n "$desc" ]; then
    scripts["$script"]="$desc"
  else
    scripts["$script"]="$script"
  fi
done < <(
  find "$SCRIPTS_DIR"/ -maxdepth 1 -type f -executable \
  | sed "s|$SCRIPTS_DIR/||" \
)

menu_entries=""

for script in "${!scripts[@]}"; do
  menu_entries+="${scripts[$script]}\n"
done
printf "$b" "$menu_entries"

selected=$(
  printf "%b" "$menu_entries" \
  | dmenu -i -l 20
)
selected_script=""

for script in "${!scripts[@]}"; do
  if [ "${scripts[$script]}" == "$selected" ]; then
    selected_script="$script"
    break
  fi
done

if [ ! -x "$SCRIPTS_DIR/$selected_script" ]; then 
  echo "No such script found!"
  exit 1 
fi

echo "Running $SCRIPTS_DIR/$selected_script..."
sh "$SCRIPTS_DIR/$selected_script"
args=$(grep '^# ARGS=' "$SCRIPTS_DIR/$selected_script")
